//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherMonitor.MelbourneWeatherTimelapse {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://MelbourneWeatherTimeLapse")]
    public partial class Exception1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Exception exceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Exception Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("Exception");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MelbourneWeatherTimeLapse")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object exception1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exception", IsNullable=true, Order=0)]
        public object Exception1 {
            get {
                return this.exception1Field;
            }
            set {
                this.exception1Field = value;
                this.RaisePropertyChanged("Exception1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MelbourneWeatherTimeLapse", ConfigurationName="MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType")]
    public interface MelbourneWeatherTimeLapsePortType {
        
        // CODEGEN: Generating message contract since the operation getLocations is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getLocations", ReplyAction="urn:getLocationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WeatherMonitor.MelbourneWeatherTimelapse.Exception1), Action="urn:getLocationsException", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WeatherMonitor.MelbourneWeatherTimelapse.getLocationsResponse getLocations(WeatherMonitor.MelbourneWeatherTimelapse.getLocationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getLocations", ReplyAction="urn:getLocationsResponse")]
        System.Threading.Tasks.Task<WeatherMonitor.MelbourneWeatherTimelapse.getLocationsResponse> getLocationsAsync(WeatherMonitor.MelbourneWeatherTimelapse.getLocationsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getWeather", ReplyAction="urn:getWeatherResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WeatherMonitor.MelbourneWeatherTimelapse.Exception1), Action="urn:getWeatherException", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WeatherMonitor.MelbourneWeatherTimelapse.getWeatherResponse getWeather(WeatherMonitor.MelbourneWeatherTimelapse.getWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getWeather", ReplyAction="urn:getWeatherResponse")]
        System.Threading.Tasks.Task<WeatherMonitor.MelbourneWeatherTimelapse.getWeatherResponse> getWeatherAsync(WeatherMonitor.MelbourneWeatherTimelapse.getWeatherRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLocationsRequest {
        
        public getLocationsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocationsResponse", WrapperNamespace="http://MelbourneWeatherTimeLapse", IsWrapped=true)]
    public partial class getLocationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MelbourneWeatherTimeLapse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public getLocationsResponse() {
        }
        
        public getLocationsResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWeather", WrapperNamespace="http://MelbourneWeatherTimeLapse", IsWrapped=true)]
    public partial class getWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MelbourneWeatherTimeLapse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string location;
        
        public getWeatherRequest() {
        }
        
        public getWeatherRequest(string location) {
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWeatherResponse", WrapperNamespace="http://MelbourneWeatherTimeLapse", IsWrapped=true)]
    public partial class getWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MelbourneWeatherTimeLapse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public getWeatherResponse() {
        }
        
        public getWeatherResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MelbourneWeatherTimeLapsePortTypeChannel : WeatherMonitor.MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MelbourneWeatherTimeLapsePortTypeClient : System.ServiceModel.ClientBase<WeatherMonitor.MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType>, WeatherMonitor.MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType {
        
        public MelbourneWeatherTimeLapsePortTypeClient() {
        }
        
        public MelbourneWeatherTimeLapsePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MelbourneWeatherTimeLapsePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MelbourneWeatherTimeLapsePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MelbourneWeatherTimeLapsePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeatherMonitor.MelbourneWeatherTimelapse.getLocationsResponse WeatherMonitor.MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType.getLocations(WeatherMonitor.MelbourneWeatherTimelapse.getLocationsRequest request) {
            return base.Channel.getLocations(request);
        }
        
        public string[] getLocations() {
            WeatherMonitor.MelbourneWeatherTimelapse.getLocationsRequest inValue = new WeatherMonitor.MelbourneWeatherTimelapse.getLocationsRequest();
            WeatherMonitor.MelbourneWeatherTimelapse.getLocationsResponse retVal = ((WeatherMonitor.MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType)(this)).getLocations(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WeatherMonitor.MelbourneWeatherTimelapse.getLocationsResponse> WeatherMonitor.MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType.getLocationsAsync(WeatherMonitor.MelbourneWeatherTimelapse.getLocationsRequest request) {
            return base.Channel.getLocationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WeatherMonitor.MelbourneWeatherTimelapse.getLocationsResponse> getLocationsAsync() {
            WeatherMonitor.MelbourneWeatherTimelapse.getLocationsRequest inValue = new WeatherMonitor.MelbourneWeatherTimelapse.getLocationsRequest();
            return ((WeatherMonitor.MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType)(this)).getLocationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeatherMonitor.MelbourneWeatherTimelapse.getWeatherResponse WeatherMonitor.MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType.getWeather(WeatherMonitor.MelbourneWeatherTimelapse.getWeatherRequest request) {
            return base.Channel.getWeather(request);
        }
        
        public string[] getWeather(string location) {
            WeatherMonitor.MelbourneWeatherTimelapse.getWeatherRequest inValue = new WeatherMonitor.MelbourneWeatherTimelapse.getWeatherRequest();
            inValue.location = location;
            WeatherMonitor.MelbourneWeatherTimelapse.getWeatherResponse retVal = ((WeatherMonitor.MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType)(this)).getWeather(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WeatherMonitor.MelbourneWeatherTimelapse.getWeatherResponse> WeatherMonitor.MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType.getWeatherAsync(WeatherMonitor.MelbourneWeatherTimelapse.getWeatherRequest request) {
            return base.Channel.getWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<WeatherMonitor.MelbourneWeatherTimelapse.getWeatherResponse> getWeatherAsync(string location) {
            WeatherMonitor.MelbourneWeatherTimelapse.getWeatherRequest inValue = new WeatherMonitor.MelbourneWeatherTimelapse.getWeatherRequest();
            inValue.location = location;
            return ((WeatherMonitor.MelbourneWeatherTimelapse.MelbourneWeatherTimeLapsePortType)(this)).getWeatherAsync(inValue);
        }
    }
}
